version: '2'
services:
  node: 
    image: node:10.3-jessie
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - ./:/var/www
    working_dir: /var/www
    command: "node app.js"
    environment:
      - NODE_ENV=production
      - CLIENT_ID=XXX
      - CLIENT_SECRET=YYY
      - CALLBACK_URL=https://example.com/twitch/webhook